# Autogenerated wrapper script for Clipper2_jll for x86_64-w64-mingw32-cxx03
export libClipper2, libClipper2Z

JLLWrappers.@generate_wrapper_header("Clipper2")
JLLWrappers.@declare_library_product(libClipper2, "libClipper2.dll")
JLLWrappers.@declare_library_product(libClipper2Z, "libClipper2Z.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libClipper2,
        "bin\\libClipper2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libClipper2Z,
        "bin\\libClipper2Z.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
